### ISSUE TITLE
Resource will not replace a server if it is not valid

### ISSUE THREAD

**Issue by whoggett** [janegilring/AzureFileSyncDsc#5] opened 2019-05-02 05:00 UTC
# ISSUE TITLE:
The endpoint is not registered if an old server with the same name is already registered.

# ISSUE DESCRIPTION:
When we rebuild a server with this resource, the existing server endpoint isn't replaced with the new server.

**Comment by whoggett** [comment] 2019-05-02 05:17
It appears to store the Azure Resource ID of the endpoint in XML format in the registry here: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Azure\StorageSync\SyncFolder

**Comment by janegilring** [comment] 2019-06-02 05:52
Thanks for reporting this.

To make sure what is happening:

1. Azure File Sync agent is installed and registered on a server
2. The server is being decommissioned
3. A new server with the same name is setup
4. Azure File Sync agent is installed on the new server, but registration fails due to an existing server endpoint with the same name being registered in the Azure File Sync service

Does this sound correct?
The desired behavior would be for the DSC resource to remove the existing server registration from Azure?

**Comment by whoggett** [comment] 2019-06-09 22:26
Yeah, that sounds correct to me. Essentially in scenarios where you build and rebuild servers but maintain the name, the server registration is not updated with the new server. It looks like it would need to be deleted and recreated.

**Comment by janegilring** [comment] 2019-07-12 13:45
The issue should be fixed by this PR:
https://github.com/janegilring/AzureFileSyncDsc/pull/6/commits/4bd795deac7d3c4a32d263583a13bc9a8771b6bd

I haven`t performed any integration test, so let me know if it does not work as intended.

**Closed as completed by janegilring** 2019-07-12 13:45 UTC
